version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fast_api_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fast_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
